### PR TITLE
Add addresses as a discovered service field + update rxandroid

### PR DESCRIPTION
**Pull request by thibmaek**
cc @jarnoverreyt @eliaslecomte

### CODE REVIEW

**Comment by asabil** [comment]
Thank you @thibmaek for this PR.

If my memory serves me right, I wasn't sure if doing the DNS resolution was the right thing to do during discovery. And I wanted to encourage the use of hostname and delay the actual IP address resolution until it was needed, such as when connecting.

Maybe I am missing something, but in which case do you need the IP addresses to be resolved during discovery?

Thanks again,
Ali

**Comment by thibmaek** [comment]
If I recall correctly, this was needed for Android.

iOS ships with its default implementation of Bonjour/zeroconf to resolve hostnames, but since Android has such a widespread and different implementation of the OS, there is no uniform way of resolving hostnames which can sometimes lead to Androids not being able to resolve hostnames via bonjour/zeroconf.

You should ask @eliaslecomte @jarnove

**Comment by asabil** [comment]
Just to be clear, I have nothing against merging this, just wanted to understand the need. Also I would like to have the android implementation updated as well before we can merge this.

**Comment by thibmaek** [comment]
Sure, let's see what the others say first

**Comment by eliaslecomte** [comment]
> Just to be clear, I have nothing against merging this, just wanted to understand the need. Also I would like to have the android implementation updated as well before we can merge this.

What would you like updated to the android implementation?

**Comment by thibmaek** [comment]
@kevinmeyvaert

**Comment by thibmaek** [comment]
> > Just to be clear, I have nothing against merging this, just wanted to understand the need. Also I would like to have the android implementation updated as well before we can merge this.
> 
> What would you like to update to the android implementation?

Prob. the implementation for adding addresses support.

**Comment by asabil** [comment]
> > > Just to be clear, I have nothing against merging this, just wanted to understand the need. Also I would like to have the android implementation updated as well before we can merge this.
> > 
> > 
> > What would you like to update to the android implementation?
> 
> Prob. the implementation for adding addresses support.

Yes, exactly. The Android version doesn't return the address list as part of the discovery.

Again, I am not sure if this should be in the discovery itself or if we should provide a separate function to solve the android case for resolving the mDNS hostnames (please note that mDNS and DNS-SD are different things, it just happens that they are very often used together).

**Comment by thibmaek** [comment]
Maybe what we needed could've been fixed better using the solution your provided i/o implementing resolving IPs for iOS in react-native-dnssd itself.

Thanks for clearing it out.

**Pull request closed without merging**
